# Generated by Django 6.0.2 on 2026-02-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="setup_steps",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
