# Generated by Django 6.0.2 on 2026-03-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_setup_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="development_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("POC", "POC"),
                    ("In Development", "In Development"),
                    ("Deployed", "Deployed"),
                ],
                default="Deployed",
                max_length=20,
            ),
        ),
    ]
