# Generated by Django 6.0.2 on 2026-03-25 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_development_notes_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="repo_link",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                default=list,
            ),
        ),
    ]
