# Generated by Django for estimated work time, priority, and deadline fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_activity_entity_roadmap_roadmapphase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='estimated_work_time',
            field=models.DurationField(null=True, blank=True, help_text='Estimated work time (hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='priority',
            field=models.CharField(max_length=10, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], null=True, blank=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='deadline',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='estimated_work_time',
            field=models.DurationField(null=True, blank=True, help_text='Estimated work time (hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='bug',
            name='priority',
            field=models.CharField(max_length=10, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], null=True, blank=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='deadline',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='improvement',
            name='estimated_work_time',
            field=models.DurationField(null=True, blank=True, help_text='Estimated work time (hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='improvement',
            name='priority',
            field=models.CharField(max_length=10, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], null=True, blank=True),
        ),
        migrations.AddField(
            model_name='improvement',
            name='deadline',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='roadmapphase',
            name='estimated_work_time',
            field=models.DurationField(null=True, blank=True, help_text='Estimated work time (hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='roadmapphase',
            name='deadline',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='estimated_work_time',
            field=models.DurationField(null=True, blank=True, help_text='Estimated work time (hh:mm:ss)'),
        ),
        migrations.AddField(
            model_name='roadmapitem',
            name='deadline',
            field=models.DateField(null=True, blank=True),
        ),
    ]
